// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	// 為了安全預設 UNKNOWN
	TransactionType_UNKNOWN  TransactionType = 0
	TransactionType_DEPOSIT  TransactionType = 1
	TransactionType_WITHDRAW TransactionType = 2
	TransactionType_TRANSFER TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEPOSIT",
		2: "WITHDRAW",
		3: "TRANSFER",
	}
	TransactionType_value = map[string]int32{
		"UNKNOWN":  0,
		"DEPOSIT":  1,
		"WITHDRAW": 2,
		"TRANSFER": 3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ledger_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_ledger_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`                            // Client 端的 UUID
	Type          TransactionType        `protobuf:"varint,2,opt,name=type,proto3,enum=pb.TransactionType" json:"type,omitempty"`                  // 交易類型
	FromAccountId int64                  `protobuf:"varint,3,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"` // 來源帳號 (DEPOSIT 時可忽略或填空)
	ToAccountId   int64                  `protobuf:"varint,4,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`       // 目標帳號 (WITHDRAW 時可忽略)
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                      // 金額 (定點數, 放大 10000 倍)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *TransferRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_UNKNOWN
}

func (x *TransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                      // e.g. "insufficient balance"
	CurrentBalance int64                  `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"` // 交易後餘額 (若是轉帳，回傳 from 的餘額)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferResponse) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

type BatchTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*TransferRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTransferRequest) Reset() {
	*x = BatchTransferRequest{}
	mi := &file_proto_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTransferRequest) ProtoMessage() {}

func (x *BatchTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTransferRequest.ProtoReflect.Descriptor instead.
func (*BatchTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *BatchTransferRequest) GetRequests() []*TransferRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*TransferResponse    `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTransferResponse) Reset() {
	*x = BatchTransferResponse{}
	mi := &file_proto_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTransferResponse) ProtoMessage() {}

func (x *BatchTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTransferResponse.ProtoReflect.Descriptor instead.
func (*BatchTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTransferResponse) GetResponses() []*TransferResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x02pb\"\xb5\x01\n" +
	"\x0fTransferRequest\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.pb.TransactionTypeR\x04type\x12&\n" +
	"\x0ffrom_account_id\x18\x03 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x04 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"o\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance\"G\n" +
	"\x14BatchTransferRequest\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.pb.TransferRequestR\brequests\"K\n" +
	"\x15BatchTransferResponse\x122\n" +
	"\tresponses\x18\x01 \x03(\v2\x14.pb.TransferResponseR\tresponses\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance*G\n" +
	"\x0fTransactionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDEPOSIT\x10\x01\x12\f\n" +
	"\bWITHDRAW\x10\x02\x12\f\n" +
	"\bTRANSFER\x10\x032\xc9\x01\n" +
	"\rLedgerService\x125\n" +
	"\bTransfer\x12\x13.pb.TransferRequest\x1a\x14.pb.TransferResponse\x12D\n" +
	"\rBatchTransfer\x12\x18.pb.BatchTransferRequest\x1a\x19.pb.BatchTransferResponse\x12;\n" +
	"\n" +
	"GetBalance\x12\x15.pb.GetBalanceRequest\x1a\x16.pb.GetBalanceResponseB(Z&github.com/JoeShih716/go-mem-ledger/pbb\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ledger_proto_goTypes = []any{
	(TransactionType)(0),          // 0: pb.TransactionType
	(*TransferRequest)(nil),       // 1: pb.TransferRequest
	(*TransferResponse)(nil),      // 2: pb.TransferResponse
	(*BatchTransferRequest)(nil),  // 3: pb.BatchTransferRequest
	(*BatchTransferResponse)(nil), // 4: pb.BatchTransferResponse
	(*GetBalanceRequest)(nil),     // 5: pb.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 6: pb.GetBalanceResponse
}
var file_proto_ledger_proto_depIdxs = []int32{
	0, // 0: pb.TransferRequest.type:type_name -> pb.TransactionType
	1, // 1: pb.BatchTransferRequest.requests:type_name -> pb.TransferRequest
	2, // 2: pb.BatchTransferResponse.responses:type_name -> pb.TransferResponse
	1, // 3: pb.LedgerService.Transfer:input_type -> pb.TransferRequest
	3, // 4: pb.LedgerService.BatchTransfer:input_type -> pb.BatchTransferRequest
	5, // 5: pb.LedgerService.GetBalance:input_type -> pb.GetBalanceRequest
	2, // 6: pb.LedgerService.Transfer:output_type -> pb.TransferResponse
	4, // 7: pb.LedgerService.BatchTransfer:output_type -> pb.BatchTransferResponse
	6, // 8: pb.LedgerService.GetBalance:output_type -> pb.GetBalanceResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		EnumInfos:         file_proto_ledger_proto_enumTypes,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
